# Generated by Django 2.1.5 on 2019-02-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapminder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarow',
            name='country',
        ),
        migrations.RemoveField(
            model_name='datarow',
            name='varname',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='chart_html',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='url',
        ),
        migrations.AddField(
            model_name='chart',
            name='filename',
            field=models.FileField(default=' ', upload_to='charts/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='DataRow',
        ),
    ]
